name: PHP CI Checks

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment via Composite Action
        uses: ./.github/actions/php-setup

      - name: Run PHPStan
        run: composer phpstan
        shell: bash

  php-cs-fixer:
    name: Run PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment via Composite Action
        uses: ./.github/actions/php-setup

      - name: Run PHP-CS-Fixer (Dry Run)
        run: PHP_CS_FIXER_IGNORE_ENV=1 composer cs-check
        shell: bash

  phpmd:
    name: Run PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment via Composite Action
        uses: ./.github/actions/php-setup

      - name: Run PHPMD
        run: composer phpmd
        shell: bash

  twig-lint:
    name: Lint Twig Templates
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment via Composite Action
        uses: ./.github/actions/php-setup

      - name: Lint Twig Templates
        run: php bin/console lint:twig templates/
        shell: bash

  security-check:
    name: Check Security Advisories
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment via Composite Action
        uses: ./.github/actions/php-setup

      - name: Check Symfony Security
        run: php bin/console security:check
        shell: bash
